services:
  - type: web
    name: nimbus-api
    runtime: go
    plan: free
    buildCommand: go build -o main main.go
    startCommand: ./main
    envVars:
      - key: DB_DRIVER
        value: postgres
      - key: DB_SOURCE
        sync: false  # This should be set manually in Render dashboard with your Neon connection string
      - key: HTTP_SERVER_ADDRESS
        value: 0.0.0.0:10000
      - key: GRPC_SERVER_ADDRESS
        value: 0.0.0.0:9090
      - key: TOKEN_SYMMETRIC_KEY
        generateValue: true
      - key: ACCESS_TOKEN_DURATION
        value: 15m
      - key: REFRESH_TOKEN_DURATION
        value: 24h
      - key: EMAIL_SENDER_NAME
        value: Nimbus
      - key: EMAIL_SENDER_ADDRESS
        sync: false  # Set manually with your email
      - key: EMAIL_SENDER_PASSWORD
        sync: false  # Set manually with your app password
      - key: REDIS_ADDRESS
        value: redis-12951.c44.us-east-1-2.ec2.redns.redis-cloud.com:12951
