services:
  - type: web
    name: nimbus-api
    runtime: go
    plan: free
    buildCommand: go build -o main main.go
    startCommand: ./main
    envVars:
      - key: DB_DRIVER
        value: postgres
      - key: HTTP_SERVER_ADDRESS
        value: 0.0.0.0:10000
      - key: GRPC_SERVER_ADDRESS
        value: 0.0.0.0:9090
      - key: ACCESS_TOKEN_DURATION
        value: 15m
      - key: REFRESH_TOKEN_DURATION
        value: 24h
      - key: EMAIL_SENDER_NAME
        value: Nimbus
