name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image with specific version
        image: postgres:17
        # Provide environment variables for postgres
        env:
          POSTGRES_PASSWORD: secret
          # IMPORTANT: Ensure this matches the user in your connection string
          POSTGRES_USER: postgres # Changed from 'root' to 'postgres'
          POSTGRES_DB: simple_bank
        # Map port 5432 to host
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5 # Updated to v5 for latest features
      with:
        go-version: '1.22' # Recommended: Use a recent stable Go version

    - name: Install migrate CLI
      run: |
        # Download and install the migrate CLI tool
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate /usr/bin/migrate

    - name: Wait for PostgreSQL to be ready
      # This step implicitly waits for the service's health check to pass
      run: echo "PostgreSQL service is ready."

    - name: Run migrations
      # Using the directly installed migrate CLI for clarity and control
      run: |
        migrate -path db/migration -database "postgresql://postgres:secret@localhost:5432/simple_bank?sslmode=disable" -verbose up
      env:
        DATABASE_URL: "postgresql://postgres:secret@localhost:5432/simple_bank?sslmode=disable"

    - name: Download Go modules
      run: go mod download

    - name: Run Tests
      # Assuming 'make test' handles running your Go tests
      run: make test